repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
        - push

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
      - id: trailing-whitespace
      - id: check-yaml

#  - repo: https://github.com/pycqa/isort
#    rev: 5.11.2
#    hooks:
#      - id: isort
#        name: isort (python)